"""initial migrations

Revision ID: 78617ef93854
Revises: 5a8ecfc5df6e
Create Date: 2019-09-26 13:27:40.408551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78617ef93854'
down_revision = '5a8ecfc5df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
