"""Initial Migration

Revision ID: 891deb5cecdf
Revises: 079a3a55ecde
Create Date: 2019-09-26 19:49:54.235547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891deb5cecdf'
down_revision = '079a3a55ecde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('number', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('age', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'age')
    op.drop_column('comments', 'number')
    # ### end Alembic commands ###
